version: '3'

services:
  mysql:
    image: csdl:latest
    container_name: csdl
    networks:
      my-network:
        ipv4_address: 172.17.0.2
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/home/thuannguyen/Downloads/datatest

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
